# Generated by Django 5.2.12 on 2026-03-16 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('target_market', models.CharField(blank=True, max_length=200)),
                ('revenue_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_size', models.CharField(max_length=100)),
                ('market_growth_rate', models.FloatField()),
                ('target_audience', models.CharField(max_length=200)),
                ('market_demand_score', models.IntegerField()),
                ('competition_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessidea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
